// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutsVideoPlayer.Infrastructure.Persistence;

#nullable disable

namespace TutsVideoPlayer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativeDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchTitle");

                    b.HasIndex("LibraryId", "RelativeDirectory")
                        .IsUnique();

                    b.HasIndex("LibraryId", "SortKey");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("CourseId", "PrimaryRelativePath")
                        .IsUnique();

                    b.HasIndex("CourseId", "SortKey");

                    b.ToTable("Lessons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lessons_DurationMs", "DurationMs IS NULL OR DurationMs > 0");

                            t.HasCheckConstraint("CK_Lessons_SourceGeneration", "SourceGeneration >= 1");
                        });
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonFolderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativeDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("CourseId", "RelativeDirectory")
                        .IsUnique();

                    b.HasIndex("CourseId", "SortKey");

                    b.ToTable("LessonFolders", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LibraryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CatalogRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSuccessfulScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogicalIdentity")
                        .IsUnique();

                    b.ToTable("Libraries", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.ScanIssueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId");

                    b.ToTable("ScanIssues", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.ScanRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CatalogRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscoveredCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("ScanRuns", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.SourceComponentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LengthBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProbeMetadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath");

                    b.HasIndex("LessonId", "Generation", "Role", "RelativePath")
                        .IsUnique();

                    b.ToTable("SourceComponents", null, t =>
                        {
                            t.HasCheckConstraint("CK_SourceComponents_LengthBytes", "LengthBytes >= 0");
                        });
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.SubtitleTrackEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<long>("LengthBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.ToTable("SubtitleTracks", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LibraryEntity", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonFolderEntity", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonFolderEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonFolderEntity", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.ScanIssueEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.ScanRunEntity", "ScanRun")
                        .WithMany()
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.SourceComponentEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", "Lesson")
                        .WithMany("SourceComponents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.SubtitleTrackEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", b =>
                {
                    b.Navigation("SourceComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
