// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutsVideoPlayer.Infrastructure.Persistence;

#nullable disable

namespace TutsVideoPlayer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915104034_QualityPreparation")]
    partial class QualityPreparation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativeDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchTitle");

                    b.HasIndex("LibraryId", "RelativeDirectory")
                        .IsUnique();

                    b.HasIndex("LibraryId", "SortKey");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("CourseId", "PrimaryRelativePath")
                        .IsUnique();

                    b.HasIndex("CourseId", "SortKey");

                    b.ToTable("Lessons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lessons_DurationMs", "DurationMs IS NULL OR DurationMs > 0");

                            t.HasCheckConstraint("CK_Lessons_SourceGeneration", "SourceGeneration >= 1");
                        });
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonFolderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativeDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("CourseId", "RelativeDirectory")
                        .IsUnique();

                    b.HasIndex("CourseId", "SortKey");

                    b.ToTable("LessonFolders", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonProgressEntity", b =>
                {
                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActiveSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastWatchedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManualCompletion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxObservedPositionMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PositionMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("LessonId", "SourceGeneration");

                    b.HasIndex("LastWatchedUtcMs");

                    b.ToTable("LessonProgress", null, t =>
                        {
                            t.HasCheckConstraint("CK_LessonProgress_LastSequence", "LastSequence >= 0");

                            t.HasCheckConstraint("CK_LessonProgress_PositionMs", "PositionMs >= 0");
                        });
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LibraryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CatalogRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSuccessfulScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogicalIdentity")
                        .IsUnique();

                    b.ToTable("Libraries", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.PlaybackSessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActiveRenditionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClosedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastHeartbeatUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedUtcMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeatUtcMs");

                    b.HasIndex("LessonId", "LastHeartbeatUtcMs");

                    b.ToTable("PlaybackSessions", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.PreferenceEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Autoplay")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FitMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PlaybackSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredQuality")
                        .HasColumnType("TEXT");

                    b.Property<bool>("QueuePaused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubtitleEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Preferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_Preferences_CacheLimitBytes", "CacheLimitBytes >= 0");
                        });
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.PreparationAttemptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SanitizedFailure")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TempRelativePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "StartedUtcMs");

                    b.ToTable("PreparationAttempts", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.PreparationJobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EnqueuedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LeaseExpiresUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("TEXT");

                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManifestRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profile")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Progress")
                        .HasColumnType("REAL");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReservedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey")
                        .IsUnique();

                    b.HasIndex("LeaseExpiresUtcMs");

                    b.HasIndex("LessonId");

                    b.HasIndex("State", "Priority", "EnqueuedUtcMs", "Id");

                    b.ToTable("PreparationJobs", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.RenditionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioCodec")
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastAccessUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManifestPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .HasColumnType("TEXT");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath");

                    b.HasIndex("Status", "RetentionClass");

                    b.HasIndex("LessonId", "SourceGeneration", "Purpose", "Profile", "RecipeVersion")
                        .IsUnique();

                    b.ToTable("Renditions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Renditions_ByteLength", "ByteLength >= 0");
                        });
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.ScanIssueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId");

                    b.ToTable("ScanIssues", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.ScanRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CatalogRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscoveredCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("ScanRuns", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.SourceComponentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LengthBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProbeMetadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath");

                    b.HasIndex("LessonId", "Generation", "Role", "RelativePath")
                        .IsUnique();

                    b.ToTable("SourceComponents", null, t =>
                        {
                            t.HasCheckConstraint("CK_SourceComponents_LengthBytes", "LengthBytes >= 0");
                        });
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.SubtitleAssociationEntity", b =>
                {
                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubtitleTrackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceGeneration")
                        .HasColumnType("INTEGER");

                    b.HasKey("LessonId", "SubtitleTrackId");

                    b.HasIndex("SubtitleTrackId");

                    b.ToTable("SubtitleAssociations", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.SubtitleTrackEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<long>("LengthBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizationVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NormalizedSourceLengthBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NormalizedSourceModifiedUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParseError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.HasIndex("CourseId", "Availability");

                    b.ToTable("SubtitleTracks", (string)null);
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LibraryEntity", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonFolderEntity", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonFolderEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonFolderEntity", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonProgressEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.PlaybackSessionEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.PreparationAttemptEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.PreparationJobEntity", "Job")
                        .WithMany("Attempts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.PreparationJobEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.RenditionEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.ScanIssueEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.ScanRunEntity", "ScanRun")
                        .WithMany()
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.SourceComponentEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", "Lesson")
                        .WithMany("SourceComponents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.SubtitleAssociationEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.SubtitleTrackEntity", "Track")
                        .WithMany()
                        .HasForeignKey("SubtitleTrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.SubtitleTrackEntity", b =>
                {
                    b.HasOne("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.CourseEntity", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.LessonEntity", b =>
                {
                    b.Navigation("SourceComponents");
                });

            modelBuilder.Entity("TutsVideoPlayer.Infrastructure.Persistence.Entities.PreparationJobEntity", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
